"use client";

import { Activity, AlertTriangle, CheckCircle2, CircleDollarSign, PackageCheck, RefreshCw, RotateCcw, ShoppingBag, Webhook } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Badge } from "./ui/badge.js";
import { Button } from "./ui/button.js";
import { Card, CardContent, CardHeader, CardTitle } from "./ui/card.js";
import { ConfirmDialog } from "./ui/dialog.js";
import { Field, Input, Textarea } from "./ui/input.js";
import { Table, TableWrap, Td, Th } from "./ui/table.js";

const adminGatewayUrl = process.env.NEXT_PUBLIC_ADMIN_GATEWAY_URL ?? "http://localhost:4001";

type Order = { orderId?: string; orderNumber?: string; customerEmail?: string; totalMinor?: number; currency?: string; status?: string; paymentStatus?: string; createdAt?: string; providerPaymentId?: string };

function money(minor = 0, currency = "USD") { return new Intl.NumberFormat("zh-CN", { style: "currency", currency }).format(minor / 100); }
function tone(status?: string): "success" | "warning" | "danger" | "neutral" { if (["paid", "captured", "completed"].includes(status ?? "")) return "success"; if (["refunded", "cancelled", "failed"].includes(status ?? "")) return "danger"; if (["pending", "pending_payment", "authorized"].includes(status ?? "")) return "warning"; return "neutral"; }

export function DashboardPage({ onOrders }: { onOrders: () => void }) {
  const [orders, setOrders] = useState<Order[]>([]);
  const [status, setStatus] = useState("正在读取订单数据");
  useEffect(() => { void fetch(`${adminGatewayUrl}/orders`).then(async (response) => { if (!response.ok) throw new Error(); const body = await response.json(); setOrders(Array.isArray(body) ? body : body.orders ?? []); setStatus("数据已同步"); }).catch(() => setStatus("订单服务暂不可用")); }, []);
  const stats = useMemo(() => {
    const today = new Date().toISOString().slice(0, 10);
    const todayOrders = orders.filter((order) => order.createdAt?.startsWith(today));
    return [
      { label: "今日 PayPal 订单", value: String(todayOrders.length), icon: ShoppingBag },
      { label: "总销售额", value: money(orders.filter((o) => o.paymentStatus === "paid").reduce((sum, o) => sum + (o.totalMinor ?? 0), 0), orders[0]?.currency), icon: CircleDollarSign },
      { label: "待发货订单", value: String(orders.filter((o) => o.status === "paid").length), icon: PackageCheck },
      { label: "退款订单", value: String(orders.filter((o) => o.paymentStatus?.includes("refund")).length), icon: RotateCcw }
    ];
  }, [orders]);
  const chartData = useMemo(() => Array.from({ length: 7 }, (_, offset) => { const date = new Date(); date.setDate(date.getDate() - (6 - offset)); const key = date.toISOString().slice(0, 10); return { day: `${date.getMonth() + 1}/${date.getDate()}`, amount: orders.filter((o) => o.createdAt?.startsWith(key)).reduce((sum, o) => sum + (o.totalMinor ?? 0) / 100, 0) }; }), [orders]);
  return <div className="space-y-6"><div className="flex items-end justify-between gap-4"><div><h1 className="text-xl font-semibold">仪表盘</h1><p className="mt-1 text-xs text-[var(--muted-foreground)]">{status}</p></div><Button size="sm" variant="outline" onClick={() => location.reload()}><RefreshCw size={14}/>刷新数据</Button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({ label, value, icon: Icon }) => <Card key={label}><CardContent className="flex items-center justify-between p-5"><div><p className="text-sm text-[var(--muted-foreground)]">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div><span className="grid size-11 place-items-center rounded-full bg-[var(--success-bg)] text-[var(--success)]"><Icon size={21}/></span></CardContent></Card>)}</div><div className="grid gap-6 xl:grid-cols-[1.05fr_1.35fr]"><Card><CardHeader><CardTitle>近 7 日订单金额</CardTitle><Badge tone="neutral">USD</Badge></CardHeader><CardContent className="h-[300px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><CartesianGrid stroke="#edf0f2" vertical={false}/><XAxis dataKey="day" axisLine={false} tickLine={false} fontSize={12}/><YAxis axisLine={false} tickLine={false} fontSize={12}/><Tooltip/><Area dataKey="amount" type="monotone" stroke="#17825f" fill="#e8f6f0" strokeWidth={2}/></AreaChart></ResponsiveContainer></CardContent></Card><Card><CardHeader><CardTitle>最新 PayPal 订单</CardTitle><Button variant="ghost" size="sm" onClick={onOrders}>查看全部</Button></CardHeader><TableWrap><Table><thead><tr><Th>订单号</Th><Th>买家</Th><Th>金额</Th><Th>状态</Th></tr></thead><tbody>{orders.slice(0,10).map((order, index) => <tr className="hover:bg-[#fafbfc]" key={order.orderId ?? index}><Td className="font-medium text-[var(--info)]">{order.orderNumber ?? order.orderId?.slice(0,8)}</Td><Td>{order.customerEmail ?? "-"}</Td><Td>{money(order.totalMinor, order.currency)}</Td><Td><Badge tone={tone(order.paymentStatus)}>{order.paymentStatus ?? order.status ?? "未知"}</Badge></Td></tr>)}{orders.length === 0 ? <tr><Td colSpan={4} className="h-40 text-center text-[var(--muted-foreground)]">暂无可展示的真实订单</Td></tr> : null}</tbody></Table></TableWrap></Card></div><Card><CardHeader><CardTitle>库存不足商品</CardTitle><Badge tone="warning">等待库存接口</Badge></CardHeader><CardContent className="flex min-h-28 items-center justify-center text-sm text-[var(--muted-foreground)]"><AlertTriangle className="mr-2" size={17}/>库存预警将在库存接口返回低库存记录后展示</CardContent></Card></div>;
}

function ConnectivityButton({ endpoint, label = "测试连通性" }: { endpoint: string; label?: string }) {
  const [state, setState] = useState<"idle"|"testing"|"ok"|"error">("idle");
  async function test() { setState("testing"); try { const response = await fetch(`${adminGatewayUrl}${endpoint}`); if (!response.ok) throw new Error(); setState("ok"); } catch { setState("error"); } }
  return <div className="flex items-center gap-3"><Button size="sm" variant="outline" onClick={() => void test()} disabled={state === "testing"}>{state === "testing" ? <RefreshCw className="animate-spin" size={14}/> : <Activity size={14}/>} {label}</Button>{state === "ok" ? <span className="flex items-center gap-1 text-xs text-[var(--success)]"><CheckCircle2 size={14}/>连接成功</span> : null}{state === "error" ? <span className="flex items-center gap-1 text-xs text-[var(--danger)]"><AlertTriangle size={14}/>连接失败</span> : null}</div>;
}

export function PaypalSettingsPage({ mode }: { mode: "sandbox" | "live" | "webhook" }) {
  const [confirm, setConfirm] = useState(false);
  const [message, setMessage] = useState("尚未保存");
  const live = mode === "live";
  const title = mode === "sandbox" ? "PayPal 沙盒配置" : live ? "PayPal 生产环境密钥" : "Webhook 订阅配置";
  return <div className="space-y-6"><div><h1 className="text-xl font-semibold">{title}</h1><p className="mt-1 text-xs text-[var(--muted-foreground)]">密钥仅提交到服务端加密存储，页面不会回显 Secret 原文。</p></div><Card><CardHeader><CardTitle>{mode === "webhook" ? "Webhook 接收与订阅" : live ? "Live 凭据" : "Sandbox 凭据"}</CardTitle><Badge tone={live ? "danger" : "info"}>{mode === "webhook" ? "异步通知" : live ? "生产环境" : "测试环境"}</Badge></CardHeader><CardContent className="space-y-5">{mode === "webhook" ? <><Field label="Webhook 接收地址"><Input readOnly value="/webhooks/paypal"/></Field><div><p className="text-sm font-medium">订阅事件</p><div className="mt-3 grid gap-3 sm:grid-cols-3">{["CHECKOUT.ORDER.APPROVED","PAYMENT.CAPTURE.COMPLETED","PAYMENT.CAPTURE.REFUNDED"].map((event) => <label className="flex items-center gap-2 rounded-lg border border-[var(--border)] p-3 text-xs" key={event}><input defaultChecked type="checkbox"/>{event}</label>)}</div></div><ConnectivityButton endpoint="/payments/provider-health" label="测试 Webhook 配置"/></> : <><Field label={`${live ? "正式" : "沙盒"} Client ID`}><Input autoComplete="off" placeholder="输入 Client ID"/></Field><Field label={`${live ? "正式" : "沙盒"} Secret`} hint="保存后仅显示已配置状态"><Input autoComplete="new-password" type="password" placeholder="输入 Secret"/></Field><ConnectivityButton endpoint="/payments/provider-health"/></>}<div className="flex items-center justify-between border-t border-[var(--border)] pt-5"><span className="text-xs text-[var(--muted-foreground)]">{message}</span><Button onClick={() => setConfirm(true)}>保存配置</Button></div></CardContent></Card><ConfirmDialog open={confirm} onOpenChange={setConfirm} title={live ? "确认更新生产密钥？" : "确认保存配置？"} description={live ? "更新后将影响真实收款。请确认 Client ID、环境和回调地址均已核对。" : "保存前请确认输入内容和环境无误。"} danger={live} confirmLabel="确认保存" onConfirm={() => setMessage("保存接口尚未接入，配置未写入")}/></div>;
}

export function RecordsPage({ kind }: { kind: "refunds" | "webhooks" | "customers" }) {
  const map = { refunds: { title: "退款记录", icon: RotateCcw, text: "退款记录将从 payment-service 查询" }, webhooks: { title: "Webhook 回调日志", icon: Webhook, text: "验签事件将从 durable inbox 查询" }, customers: { title: "买家列表", icon: ShoppingBag, text: "买家资料将从客户接口查询" } } as const;
  const meta = map[kind]; const Icon = meta.icon;
  const [records,setRecords]=useState<Array<Record<string,unknown>>>([]); const [loading,setLoading]=useState(false); const [loadState,setLoadState]=useState("尚未刷新");
  async function load(){setLoading(true);try{const endpoint=kind==="refunds"?"/payments/refunds":kind==="webhooks"?"/payments/webhooks":"/customers";const response=await fetch(`${adminGatewayUrl}${endpoint}`);if(!response.ok)throw new Error();const body=await response.json();setRecords(Array.isArray(body)?body:body.items??[]);setLoadState("数据已同步");}catch{setRecords([]);setLoadState("接口暂不可用");}finally{setLoading(false);}}
  useEffect(()=>{void load();},[kind]);
  return <div className="space-y-6"><div><h1 className="text-xl font-semibold">{meta.title}</h1><p className="mt-1 text-xs text-[var(--muted-foreground)]">只展示后端返回的真实记录 · {loadState}</p></div><Card><CardHeader><CardTitle>{meta.title}</CardTitle><Button size="sm" variant="outline" disabled={loading} onClick={()=>void load()}><RefreshCw className={loading?"animate-spin":""} size={14}/>刷新</Button></CardHeader>{records.length?<TableWrap><Table><thead><tr>{kind==="refunds"?<><Th>退款 ID</Th><Th>订单 ID</Th><Th>金额</Th><Th>状态</Th><Th>操作人</Th><Th>时间</Th></>:kind==="webhooks"?<><Th>事件 ID</Th><Th>事件类型</Th><Th>关联订单</Th><Th>状态</Th><Th>尝试</Th><Th>接收时间</Th></>:<><Th>买家</Th><Th>邮箱</Th><Th>订单数</Th><Th>状态</Th></>}</tr></thead><tbody>{records.map((record,index)=><tr className="hover:bg-[#fafbfc]" key={String(record.refundId??record.eventId??index)}>{kind==="refunds"?<><Td className="font-medium">{String(record.providerRefundId??record.refundId??"-")}</Td><Td>{String(record.orderId??"-")}</Td><Td>{money(Number(record.amountMinor??0),String(record.currency??"USD"))}</Td><Td><Badge tone={tone(String(record.status??""))}>{String(record.status??"-")}</Badge></Td><Td>{String(record.actorId??"-")}</Td><Td>{String(record.createdAt??"-").replace("T"," ").slice(0,16)}</Td></>:kind==="webhooks"?<><Td className="font-medium">{String(record.eventId??"-")}</Td><Td>{String(record.eventType??"-")}</Td><Td>{String(record.orderId??"-")}</Td><Td><Badge tone={tone(String(record.status??""))}>{String(record.status??"-")}</Badge></Td><Td>{String(record.attemptCount??0)}/{String(record.maxAttempts??0)}</Td><Td>{String(record.receivedAt??"-").replace("T"," ").slice(0,16)}</Td></>:<><Td>{String(record.name??"-")}</Td><Td>{String(record.email??"-")}</Td><Td>{String(record.orderCount??0)}</Td><Td><Badge>{String(record.status??"-")}</Badge></Td></>}</tr>)}</tbody></Table></TableWrap>:<CardContent className="flex min-h-[320px] flex-col items-center justify-center text-center"><span className="grid size-12 place-items-center rounded-full bg-[var(--muted)] text-[var(--muted-foreground)]"><Icon size={21}/></span><p className="mt-4 text-sm font-medium">暂无记录</p><p className="mt-1 text-xs text-[var(--muted-foreground)]">{meta.text}</p></CardContent>}</Card></div>;
}

export function SiteSettingsPage() { const [open,setOpen]=useState(false); return <div className="space-y-6"><h1 className="text-xl font-semibold">网站基础配置</h1><Card><CardHeader><CardTitle>店铺信息</CardTitle></CardHeader><CardContent className="grid gap-5 lg:grid-cols-2"><Field label="后台名称"><Input defaultValue="工艺品跨境管理后台"/></Field><Field label="默认币种"><select className="h-9 rounded-lg border border-[var(--border)] px-3 text-sm"><option>USD</option><option>EUR</option><option>GBP</option></select></Field><Field label="客服联系邮箱"><Input type="email" placeholder="support@example.com"/></Field><Field label="订单时区"><Input defaultValue="Asia/Hong_Kong"/></Field><div className="lg:col-span-2"><Field label="网站备注"><Textarea placeholder="仅供内部运营人员查看"/></Field></div><div className="lg:col-span-2 flex justify-end"><Button onClick={()=>setOpen(true)}>保存设置</Button></div></CardContent></Card><ConfirmDialog open={open} onOpenChange={setOpen} title="确认保存网站配置？" description="基础配置会影响后台显示和订单默认值，请确认后继续。" onConfirm={()=>undefined}/></div>; }
